config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  Rails.application.routes.draw do
  resources :lists, only: [:index, :new, :show, :create] do
  resources :bookmarks, only: [:new, :create]
  end
  end
  # Defines the root path route ("/")
  # root "posts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length:{minimum:6}
  validates :movie, uniqueness: {scope: :list}
end

app/models/list.rb
class List < ApplicationRecord
has_many :bookmarks, dependent: :destroy
has_many :movies, through: :bookmarks
has_one_attached :photo
validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
has_many :bookmarks
has_many :lists, through: :bookmarks

validates :title, presence: true,  uniqueness: true
validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
def new
  @list = List.find(params[:list_id])
  @bookmark = Bookmark.new
  end

  def create
    @bookmark = List.new(list_params)
    if  @bookmark.save
      redirect_to bookmark_path(@bookmar)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if  @list.save
      redirect_to lists_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
<%= f.input :comment %>
   <%= f.submit 'Add', class: 'btn btn mt-2' %>
<% end %>

app/views/bookmarks/new.html.erb
<h1>Bookmark</h1>
<%= render 'form', bookmark: @bookmark %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
   <%= f.submit 'Add', class: 'btn mt-2' %>
<% end %>

app/views/lists/index.html.erb
<div class ="container">
  <div class ="wrapper">
  <h1> Movies </h1>
<div class="cards">
  <% @lists.each do |list|%>
 <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? cl_image_path(list.photo.key) : image_path('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPQDYau3Hs4-xw1i8jVSUY4BlF4FLmg8lQqg&usqp=CAU') %>)">
  <%= link_to list.name, list_path(list)%>
  </div>
<% end %>
  </div>
<%= link_to "New List", new_list_path%>
</div>

app/views/lists/new.html.erb
<div class= "container">
<h1>Create New List</h1>
<%= render 'form', list: @list %>
</div>

app/views/lists/show.html.erb
<h1><%= @list.name%></h1>